import { ThemeVariables } from '../types';

export const darkTheme: ThemeVariables = {
    // Global
    '--aeva-font-family': "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
    '--aeva-page-bg': '#1a1a1a',
    '--aeva-page-gradient': 'radial-gradient(circle, #2c3e50 0%, #000000 100%)',
    '--aeva-primary-color': '#818cf8',
    '--aeva-primary-hover': '#6366f1',
    '--aeva-secondary-color': '#9ca3af',
    '--aeva-text-color': '#f9fafb',
    '--aeva-text-muted': '#9ca3af',
    '--aeva-card-bg': '#2a2a2a',
    '--aeva-card-border-color': '#4b5563',
    '--aeva-card-border-hover-color': '#818cf8',
    '--aeva-card-border-radius': '12px',
    '--aeva-card-transition': 'all 0.2s ease',
    '--aeva-card-padding-sm': '1rem',
    '--aeva-card-padding-md': '1.5rem',
    '--aeva-card-padding-lg': '2rem',

    // Button
    '--aeva-button-font-family': "inherit",
    '--aeva-button-border-radius': '50vh',
    '--aeva-button-transition': 'all 0.2s ease-in-out',
    '--aeva-button-gap': '8px',
    '--aeva-button-focus-ring-color': '#818cf8',
    '--aeva-button-focus-ring-width': '3px',
    '--aeva-button-focus-ring-offset': '2px',
    '--aeva-button-primary-bg': '#818cf8',
    '--aeva-button-primary-color': '#1a1a1a',
    '--aeva-button-primary-hover-bg': '#6366f1',
    '--aeva-button-primary-active-bg': '#4f46e5',
    '--aeva-button-secondary-bg': '#4b5563',
    '--aeva-button-secondary-color': '#ffffff',
    '--aeva-button-secondary-hover-bg': '#374151',
    '--aeva-button-secondary-active-bg': '#1f2937',
    '--aeva-button-outline-border-color': '#818cf8',
    '--aeva-button-outline-color': '#818cf8',
    '--aeva-button-outline-hover-bg': 'rgba(129, 140, 248, 0.1)',
    '--aeva-button-outline-active-bg': 'rgba(129, 140, 248, 0.2)',
    '--aeva-button-ghost-color': '#818cf8',
    '--aeva-button-ghost-hover-bg': 'rgba(129, 140, 248, 0.1)',
    '--aeva-button-ghost-active-bg': 'rgba(129, 140, 248, 0.2)',
    '--aeva-button-danger-bg': '#ef4444',
    '--aeva-button-danger-color': '#ffffff',
    '--aeva-button-danger-hover-bg': '#dc2626',
    '--aeva-button-danger-active-bg': '#b91c1c',
    '--aeva-button-disabled-opacity': '0.4',
    '--aeva-button-disabled-cursor': 'not-allowed',
    '--aeva-button-padding-sm': '8px 32px',
    '--aeva-button-font-size-sm': '14px',
    '--aeva-button-padding-md': '12px 48px',
    '--aeva-button-font-size-md': '16px',
    '--aeva-button-padding-lg': '16px 64px',
    '--aeva-button-font-size-lg': '18px',
    '--aeva-button-icon-padding-sm': '10px',
    '--aeva-button-icon-width-sm': '44px',
    '--aeva-button-icon-padding-md': '12px',
    '--aeva-button-icon-width-md': '44px',
    '--aeva-button-icon-padding-lg': '14px',
    '--aeva-button-icon-width-lg': '48px',

    // Input
    '--aeva-input-font-family': "inherit",
    '--aeva-input-border-radius': '8px',
    '--aeva-input-transition': 'all 0.2s ease-in-out',
    '--aeva-input-bg': '#1f2937',
    '--aeva-input-border-color': '#4b5563',
    '--aeva-input-text-color': '#f9fafb',
    '--aeva-input-placeholder-color': '#6b7280',
    '--aeva-input-error-border-color': '#ef4444',
    '--aeva-input-focus-border-color': '#3b82f6',
    '--aeva-input-focus-ring-color': 'rgba(59, 130, 246, 0.3)',
    '--aeva-input-focus-ring-width': '3px',
    '--aeva-input-focus-ring-offset': '0px',
    '--aeva-input-hover-border-color': '#6b7280',
    '--aeva-input-disabled-bg': '#111827',
    '--aeva-input-disabled-border-color': '#374151',
    '--aeva-input-disabled-text-color': '#6b7280',
    '--aeva-input-disabled-opacity': '0.5',
    '--aeva-input-flat-bg': 'transparent',
    '--aeva-input-flat-hover-bg': 'rgba(255, 255, 255, 0.05)',
    '--aeva-input-flat-focus-bg': 'rgba(255, 255, 255, 0.1)',
    '--aeva-input-padding-sm': '8px 12px',
    '--aeva-input-font-size-sm': '14px',
    '--aeva-input-height-sm': '36px',
    '--aeva-input-padding-md': '12px 16px',
    '--aeva-input-font-size-md': '16px',
    '--aeva-input-height-md': '44px',
    '--aeva-input-padding-lg': '16px 20px',
    '--aeva-input-font-size-lg': '18px',
    '--aeva-input-height-lg': '52px',
    '--aeva-input-multiline-min-height': '100px',

    // Badge
    '--aeva-badge-font-family': "inherit",
    '--aeva-badge-border-radius': '16px',
    '--aeva-badge-transition': 'all 0.2s ease-in-out',
    '--aeva-badge-gap': '6px',
    '--aeva-badge-primary-bg': '#1e1b4b',
    '--aeva-badge-primary-color': '#818cf8',
    '--aeva-badge-primary-border': '#312e81',
    '--aeva-badge-secondary-bg': '#1f2937',
    '--aeva-badge-secondary-color': '#9ca3af',
    '--aeva-badge-secondary-border': '#374151',
    '--aeva-badge-success-bg': '#064e3b',
    '--aeva-badge-success-color': '#34d399',
    '--aeva-badge-success-border': '#065f46',
    '--aeva-badge-warning-bg': '#78350f',
    '--aeva-badge-warning-color': '#fbbf24',
    '--aeva-badge-warning-border': '#92400e',
    '--aeva-badge-danger-bg': '#7f1d1d',
    '--aeva-badge-danger-color': '#f87171',
    '--aeva-badge-danger-border': '#991b1b',
    '--aeva-badge-info-bg': '#1e3a8a',
    '--aeva-badge-info-color': '#60a5fa',
    '--aeva-badge-info-border': '#1e40af',
    '--aeva-badge-padding-sm': '4px 10px',
    '--aeva-badge-font-size-sm': '12px',
    '--aeva-badge-padding-md': '6px 12px',
    '--aeva-badge-font-size-md': '14px',
    '--aeva-badge-padding-lg': '8px 16px',
    '--aeva-badge-font-size-lg': '16px',
    '--aeva-badge-delete-size': '16px',
    '--aeva-badge-delete-hover-bg': 'rgba(255, 255, 255, 0.1)',

    // Modal
    '--aeva-modal-bg': 'rgba(31, 41, 55, 0.8)',
    '--aeva-modal-backdrop-bg': 'rgba(0, 0, 0, 0.6)',
    '--aeva-modal-border-color': 'rgba(255, 255, 255, 0.1)',
    '--aeva-modal-shadow-color': 'rgba(0, 0, 0, 0.5)',
    '--aeva-modal-blur': '20px',
    '--aeva-modal-padding': '2rem',
    '--aeva-modal-max-width': '600px',
    '--aeva-modal-border-radius': '24px',
    '--aeva-modal-shimmer-gradient': 'linear-gradient(90deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.3) 50%, rgba(255, 255, 255, 0.1) 100%)',

    // Progress
    '--aeva-progress-color': '#3b82f6',
    '--aeva-progress-bg': '#374151',
    '--aeva-progress-thickness': '8px',
    '--aeva-progress-border-radius': '999px',
    '--aeva-progress-label-color': '#f3f4f6',
    '--aeva-progress-size-sm': '80px',
    '--aeva-progress-size-md': '120px',
    '--aeva-progress-size-lg': '160px',
    '--aeva-progress-animation-duration': '1.5s',
    '--aeva-progress-label-font-size': '14px',

    // Radio
    '--aeva-radio-unchecked-stroke': '#4b5563',
    '--aeva-radio-checked-stroke': '#3b82f6',
    '--aeva-radio-checked-bg': '#3b82f6',
    '--aeva-radio-checkmark-color': '#ffffff',
    '--aeva-radio-size': '20px',
    '--aeva-radio-transition': 'all 0.2s ease-in-out',
    '--aeva-radio-disabled-opacity': '0.5',

    // Checkbox
    '--aeva-checkbox-unchecked-stroke': '#4b5563',
    '--aeva-checkbox-checked-stroke': '#3b82f6',
    '--aeva-checkbox-checked-bg': '#3b82f6',
    '--aeva-checkbox-checkmark-color': '#ffffff',
    '--aeva-checkbox-size': '20px',
    '--aeva-checkbox-border-radius': '6px',
    '--aeva-checkbox-transition': 'all 0.2s ease-in-out',
    '--aeva-checkbox-disabled-opacity': '0.5',

    // Rating
    '--aeva-rating-color': '#fbbf24',
    '--aeva-rating-empty-color': '#374151',
    '--aeva-rating-hover-color': '#f59e0b',
    '--aeva-rating-label-color': '#9ca3af',
    '--aeva-rating-size-sm': '16px',
    '--aeva-rating-size-md': '24px',
    '--aeva-rating-size-lg': '32px',

    // Tooltip
    '--aeva-tooltip-bg': 'rgba(0, 0, 0, 0.95)',
    '--aeva-tooltip-color': '#ffffff',
    '--aeva-tooltip-blur': '12px',
    '--aeva-tooltip-border-radius': '8px',
    '--aeva-tooltip-padding': '0.5rem 0.75rem',
    '--aeva-tooltip-font-size': '0.875rem',
    '--aeva-tooltip-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.4)',

    // Icon
    '--aeva-icon-bg': '#374151',
    '--aeva-icon-color': '#818cf8',
    '--aeva-icon-border-color': '#ffffff',
    '--aeva-icon-border-width': '2px',
    '--aeva-icon-size-sm': '40px',
    '--aeva-icon-size-md': '56px',
    '--aeva-icon-size-lg': '72px',

    // List Item
    '--aeva-list-item-padding': '12px 16px',
    '--aeva-list-item-gap': '16px',
    '--aeva-list-item-bg': 'transparent',
    '--aeva-list-item-color': '#f9fafb',
    '--aeva-list-item-hover-bg': 'rgba(255, 255, 255, 0.08)',
    '--aeva-list-item-active-bg': 'rgba(102, 126, 234, 0.15)',
    '--aeva-list-item-border-radius': '0',
    '--aeva-list-item-transition': 'background-color 0.2s ease',

    // Page
    '--aeva-page-background': '#1a1a1a',
    '--aeva-page-animation-duration': '350ms',
    '--aeva-page-backdrop-bg': 'rgba(0, 0, 0, 0.7)',
    '--aeva-page-z-index': '2000',

    // Popup Menu
    '--aeva-popup-bg': 'rgba(31, 41, 55, 0.8)',
    '--aeva-popup-border-radius': '23px',
    '--aeva-popup-min-width': '200px',
    '--aeva-popup-max-width': '600px',
    '--aeva-popup-blur': '15px',
    '--aeva-popup-border-color': 'rgba(255, 255, 255, 0.1)',
    '--aeva-popup-shadow-color': 'rgba(0, 0, 0, 0.5)',

    // Ripple
    '--aeva-ripple-color': 'currentColor',
    '--aeva-ripple-duration': '600ms',
    '--aeva-ripple-opacity': '0.2',

    // Tab Item
    '--aeva-tab-item-font-family': "inherit",
    '--aeva-tab-item-font-size': '14px',
    '--aeva-tab-item-padding': '8px 16px',
    '--aeva-tab-item-border-radius': '8px',
    '--aeva-tab-item-transition': 'color 0.2s ease-in-out',
    '--aeva-tab-item-color-active': '#ffffff',
    '--aeva-tab-item-color-inactive': 'rgba(255, 255, 255, 0.5)',
    '--aeva-tab-item-color-disabled': 'rgba(255, 255, 255, 0.2)',
    '--aeva-tab-item-cursor': 'pointer',
    '--aeva-tab-item-disabled-opacity': '0.4',

    // Text
    '--aeva-text-font-family': "inherit",
    '--aeva-text-max-width': 'none',
    '--aeva-text-display-font-family': "inherit",
    '--aeva-text-display-weight': '800',
    '--aeva-text-display-line-height': '1.1',
    '--aeva-text-letter-spacing-display': '-0.02em',
    '--aeva-text-heading-font-family': "inherit",
    '--aeva-text-heading-weight': '700',
    '--aeva-text-heading-line-height': '1.2',
    '--aeva-text-letter-spacing-heading': '-0.01em',
    '--aeva-text-body-font-family': "inherit",
    '--aeva-text-body-weight': '400',
    '--aeva-text-body-line-height': '1.6',
    '--aeva-text-letter-spacing-body': 'normal',
    '--aeva-text-label-font-family': "inherit",
    '--aeva-text-label-weight': '500',
    '--aeva-text-label-line-height': '1.4',
    '--aeva-text-letter-spacing-label': '0.01em',
    '--aeva-text-size-xs': '0.75rem',
    '--aeva-text-size-sm': '0.875rem',
    '--aeva-text-size-md': '1rem',
    '--aeva-text-size-lg': '1.125rem',
    '--aeva-text-size-xl': '1.25rem',
    '--aeva-text-size-2xl': '1.5rem',
    '--aeva-text-size-3xl': '1.875rem',
    '--aeva-text-muted-color': '#9ca3af',
    '--aeva-text-inverse-color': '#1a1a1a',
    '--aeva-text-error-color': '#f87171',
    '--aeva-text-link-color': '#818cf8',
    '--aeva-text-link-hover-color': '#6366f1',
    '--aeva-text-code-bg': 'rgba(255, 255, 255, 0.1)',

    // Action Bar
    '--aeva-action-bar-bg': 'transparent',
    '--aeva-action-bar-padding': '1rem',
    '--aeva-action-bar-gap': '0.75rem',
    '--aeva-action-bar-border-top': 'none',
    '--aeva-action-bar-border-bottom': 'none',
    '--aeva-action-bar-backdrop-filter': 'none',
    '--aeva-action-bar-drop-shadow': 'none',
    '--aeva-action-bar-sticky-bg': 'rgba(31, 41, 55, 0.95)',
    '--aeva-action-bar-sticky-blur': '12px',
    '--aeva-action-bar-glassmorphism-border': '1px solid rgba(255, 255, 255, 0.1)',
    '--aeva-action-bar-glassmorphism-shadow': '0 -2px 8px rgba(0, 0, 0, 0.3)',

    // Carousel
    '--aeva-carousel-height': '400px',
    '--aeva-carousel-nav-bg': 'rgba(0, 0, 0, 0.6)',
    '--aeva-carousel-nav-color': 'white',
    '--aeva-carousel-nav-hover-bg': 'rgba(0, 0, 0, 0.8)',
    '--aeva-carousel-indicator-color': 'rgba(255, 255, 255, 0.3)',
    '--aeva-carousel-indicator-active-color': 'white',
    '--aeva-carousel-indicator-hover-bg': 'rgba(255, 255, 255, 0.9)',
    '--aeva-carousel-transition-duration': '300ms',

    // List
    '--aeva-list-padding': '0',
    '--aeva-list-gap': '0',
    '--aeva-list-border-radius': '23px',

    // Tab
    '--aeva-tab-bg': 'rgba(255, 255, 255, 0.05)',
    '--aeva-tab-active-bg': 'rgba(255, 255, 255, 0.1)',
    '--aeva-tab-padding': '12px',
    '--aeva-tab-gap': '12px',
    '--aeva-tab-border-radius': '50vh',
    '--aeva-tab-transition-duration': '300ms',
    '--aeva-tab-transition-timing': 'cubic-bezier(0.4, 0, 0.2, 1)',

    // Toast
    '--aeva-toast-bg': 'rgba(31, 41, 55, 0.9)',
    '--aeva-toast-border-radius': '12px',
    '--aeva-toast-padding': '1rem 1.25rem',
    '--aeva-toast-min-width': '300px',
    '--aeva-toast-max-width': '500px',
    '--aeva-toast-blur': '12px',
    '--aeva-toast-border-color': 'rgba(255, 255, 255, 0.1)',
    '--aeva-toast-shadow-color': 'rgba(0, 0, 0, 0.5)',
    '--aeva-toast-close-hover-bg': 'rgba(255, 255, 255, 0.1)',

    // Grid & Stack Gaps
    '--aeva-grid-gap-none': '0',
    '--aeva-grid-gap-xs': '0.25rem',
    '--aeva-grid-gap-sm': '0.5rem',
    '--aeva-grid-gap-md': '1rem',
    '--aeva-grid-gap-lg': '1.5rem',
    '--aeva-grid-gap-xl': '2rem',
    '--aeva-grid-auto-min-width': '250px',
    '--aeva-grid-auto-max-width': '1fr',

    '--aeva-stack-gap-none': '0',
    '--aeva-stack-gap-xs': '0.25rem',
    '--aeva-stack-gap-sm': '0.5rem',
    '--aeva-stack-gap-md': '1rem',
    '--aeva-stack-gap-lg': '1.5rem',
    '--aeva-stack-gap-xl': '2rem',

    // Bento Grid
    '--aeva-bento-grid-gap': '1rem',
    '--aeva-bento-grid-min-height': '200px',

    // Section
    '--aeva-section-gap': '0',
    '--aeva-section-padding': '0',
    '--aeva-section-header-padding': '0',
    '--aeva-section-body-padding': '0',
    '--aeva-section-footer-padding': '0',

    // Sidebar
    '--aeva-sidebar-bg': '#2a2a2a',
    '--aeva-sidebar-width-sm': '200px',
    '--aeva-sidebar-width-md': '280px',
    '--aeva-sidebar-width-lg': '320px',
    '--aeva-sidebar-icon-width': '72px',
    '--aeva-sidebar-transition': '0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    '--aeva-sidebar-z-index': '1000',
    '--aeva-sidebar-shadow': '2px 0 8px rgba(0, 0, 0, 0.3)',
    '--aeva-sidebar-backdrop-bg': 'rgba(0, 0, 0, 0.7)',
    '--aeva-sidebar-border': '1px solid rgba(255, 255, 255, 0.1)',
    '--aeva-sidebar-glassmorphism-bg': 'rgba(31, 41, 55, 0.95)',
    '--aeva-sidebar-glassmorphism-border': 'rgba(255, 255, 255, 0.1)',
    '--aeva-sidebar-scrollbar-thumb': '#4b5563',
    '--aeva-sidebar-scrollbar-thumb-hover': '#6b7280',

    // Container
    '--aeva-container-max-width-sm': '640px',
    '--aeva-container-max-width-md': '768px',
    '--aeva-container-max-width-lg': '1024px',
    '--aeva-container-max-width-xl': '1280px',
    '--aeva-container-max-width-full': '100%',
    '--aeva-container-padding-none': '0',
    '--aeva-container-padding-sm': '1rem',
    '--aeva-container-padding-md': '1.5rem',
    '--aeva-container-padding-lg': '2rem',

    // Grid Item
    '--aeva-grid-item-min-height': 'auto',

    // Masonry
    '--aeva-masonry-gap': '16px',
    '--aeva-masonry-column-count': 'auto'
};
