import { ThemeVariables } from '../types';
import { sharedTokens } from './token';
import { colorTokens } from './color';

export const darkTheme: ThemeVariables = {
  ...sharedTokens,
  ...colorTokens,
  // Global
  '--aeva-font-family':
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
  '--aeva-page-bg': 'var(--aeva-color-gray-900)',
  '--aeva-page-gradient':
    'radial-gradient(circle, var(--aeva-color-gray-800) 0%, var(--aeva-color-black) 100%)',
  '--aeva-primary-color': 'var(--aeva-color-indigo-400)',
  '--aeva-primary-hover': 'var(--aeva-color-indigo-300)',
  '--aeva-secondary-color': 'var(--aeva-color-gray-400)',
  '--aeva-text-color': 'var(--aeva-color-gray-50)',
  '--aeva-text-muted': 'var(--aeva-color-gray-400)',
  '--aeva-accent-gold': '#fbbf24',
  '--aeva-surface-tertiary': '#0d0f12',
  '--aeva-surface-glass': 'rgba(31, 41, 55, 0.9)',
  '--aeva-card-bg': 'var(--aeva-color-gray-800)',
  '--aeva-card-border-color': 'var(--aeva-color-gray-700)',
  '--aeva-card-border-width': 'var(--aeva-border-thin)',
  '--aeva-card-border-hover-color': 'var(--aeva-color-indigo-400)',
  '--aeva-card-transition': 'var(--aeva-transition-normal)',
  '--aeva-card-padding-sm': 'var(--aeva-space-sm)',
  '--aeva-card-padding-md': 'var(--aeva-space-md)',
  '--aeva-card-padding-lg': 'var(--aeva-space-lg)',

  // Button
  '--aeva-button-font-family': 'inherit',
  '--aeva-button-border-radius': '50vh',
  '--aeva-button-transition': 'var(--aeva-transition-normal)',
  '--aeva-button-gap': 'var(--aeva-space-xs)',
  '--aeva-button-focus-ring-color': 'var(--aeva-color-indigo-400)',
  '--aeva-button-focus-ring-width': '3px',
  '--aeva-button-focus-ring-offset': '2px',
  '--aeva-button-primary-bg': 'var(--aeva-color-indigo-400)',
  '--aeva-button-primary-color': 'var(--aeva-color-gray-900)',
  '--aeva-button-primary-hover-bg': 'var(--aeva-color-indigo-300)',
  '--aeva-button-primary-active-bg': 'var(--aeva-color-indigo-200)',
  '--aeva-button-secondary-bg': 'var(--aeva-color-gray-700)',
  '--aeva-button-secondary-color': 'var(--aeva-color-white)',
  '--aeva-button-secondary-hover-bg': 'var(--aeva-color-gray-600)',
  '--aeva-button-secondary-active-bg': 'var(--aeva-color-gray-500)',
  '--aeva-button-outline-border-color': 'var(--aeva-color-indigo-400)',
  '--aeva-button-outline-color': 'var(--aeva-color-indigo-400)',
  '--aeva-button-outline-hover-bg': 'rgba(129, 140, 248, 0.1)',
  '--aeva-button-outline-active-bg': 'rgba(129, 140, 248, 0.2)',
  '--aeva-button-ghost-color': 'var(--aeva-color-indigo-400)',
  '--aeva-button-ghost-hover-bg': 'rgba(129, 140, 248, 0.1)',
  '--aeva-button-ghost-active-bg': 'rgba(129, 140, 248, 0.2)',
  '--aeva-button-danger-bg': 'var(--aeva-color-red-500)',
  '--aeva-button-danger-color': 'var(--aeva-color-white)',
  '--aeva-button-danger-hover-bg': 'var(--aeva-color-red-600)',
  '--aeva-button-danger-active-bg': 'var(--aeva-color-red-700)',
  '--aeva-button-disabled-opacity': '0.4',
  '--aeva-button-disabled-cursor': 'not-allowed',
  '--aeva-button-padding-sm': 'var(--aeva-space-xs) var(--aeva-space-lg)',
  '--aeva-button-font-size-sm': 'var(--aeva-font-size-sm)',
  '--aeva-button-padding-md': 'var(--aeva-space-smd) var(--aeva-space-xl)',
  '--aeva-button-font-size-md': 'var(--aeva-font-size-sm)',
  '--aeva-button-padding-lg': 'var(--aeva-space-sm) var(--aeva-space-2xl)',
  '--aeva-button-font-size-lg': 'var(--aeva-font-size-md)',
  '--aeva-button-icon-padding-sm': 'var(--aeva-space-xs)',
  '--aeva-button-icon-width-sm': '2.75rem',
  '--aeva-button-icon-padding-md': 'var(--aeva-space-smd)',
  '--aeva-button-icon-width-md': '3rem',
  '--aeva-button-icon-padding-lg': 'var(--aeva-space-sm)',
  '--aeva-button-icon-width-lg': '3.5rem',

  // Input
  '--aeva-input-font-family': 'inherit',
  '--aeva-input-transition': 'var(--aeva-transition-normal)',
  '--aeva-input-bg': 'var(--aeva-color-gray-800)',
  '--aeva-input-border-color': 'var(--aeva-color-gray-700)',
  '--aeva-input-text-color': '#f9fafb',
  '--aeva-input-placeholder-color': 'var(--aeva-color-gray-500)',
  '--aeva-input-error-border-color': 'var(--aeva-color-red-500)',
  '--aeva-input-focus-border-color': 'var(--aeva-color-blue-500)',
  '--aeva-input-focus-ring-color': 'rgba(59, 130, 246, 0.3)',
  '--aeva-input-focus-ring-width': '3px',
  '--aeva-input-focus-ring-offset': '0px',
  '--aeva-input-hover-border-color': 'var(--aeva-color-gray-500)',
  '--aeva-input-disabled-bg': 'var(--aeva-color-gray-950)',
  '--aeva-input-disabled-border-color': 'var(--aeva-color-gray-800)',
  '--aeva-input-disabled-text-color': 'var(--aeva-color-gray-500)',
  '--aeva-input-disabled-opacity': '0.5',
  '--aeva-input-flat-bg': 'transparent',
  '--aeva-input-flat-hover-bg': 'rgba(255, 255, 255, 0.05)',
  '--aeva-input-flat-focus-bg': 'rgba(255, 255, 255, 0.1)',
  '--aeva-input-padding-sm': 'var(--aeva-space-xs) var(--aeva-space-smd)',
  '--aeva-input-font-size-sm': 'var(--aeva-font-size-sm)',
  '--aeva-input-height-sm': '2.25rem',
  '--aeva-input-padding-md': 'var(--aeva-space-smd) var(--aeva-space-sm)',
  '--aeva-input-font-size-md': 'var(--aeva-font-size-sm)',
  '--aeva-input-height-md': '2.75rem',
  '--aeva-input-padding-lg': 'var(--aeva-space-sm) var(--aeva-space-xl)',
  '--aeva-input-font-size-lg': 'var(--aeva-font-size-md)',
  '--aeva-input-height-lg': '3.25rem',
  '--aeva-input-multiline-min-height': '100px',

  // Badge
  '--aeva-badge-font-family': 'inherit',
  '--aeva-badge-border-radius': '16px',
  '--aeva-badge-transition': 'var(--aeva-transition-normal)',
  '--aeva-badge-gap': '6px',
  '--aeva-badge-primary-bg': 'var(--aeva-color-indigo-950)',
  '--aeva-badge-primary-color': 'var(--aeva-color-indigo-400)',
  '--aeva-badge-primary-border': 'var(--aeva-color-indigo-900)',
  '--aeva-badge-secondary-bg': 'var(--aeva-color-gray-800)',
  '--aeva-badge-secondary-color': 'var(--aeva-color-gray-400)',
  '--aeva-badge-secondary-border': 'var(--aeva-color-gray-700)',
  '--aeva-badge-success-bg': 'var(--aeva-color-green-950)',
  '--aeva-badge-success-color': 'var(--aeva-color-green-400)',
  '--aeva-badge-success-border': 'var(--aeva-color-green-900)',
  '--aeva-badge-warning-bg': 'var(--aeva-color-yellow-950)',
  '--aeva-badge-warning-color': 'var(--aeva-color-yellow-400)',
  '--aeva-badge-warning-border': 'var(--aeva-color-yellow-900)',
  '--aeva-badge-danger-bg': 'var(--aeva-color-red-950)',
  '--aeva-badge-danger-color': 'var(--aeva-color-red-400)',
  '--aeva-badge-danger-border': 'var(--aeva-color-red-900)',
  '--aeva-badge-info-bg': 'var(--aeva-color-blue-950)',
  '--aeva-badge-info-color': 'var(--aeva-color-blue-400)',
  '--aeva-badge-info-border': 'var(--aeva-color-blue-900)',
  '--aeva-badge-padding-sm': 'var(--aeva-space-xxs) var(--aeva-space-xs)',
  '--aeva-badge-font-size-sm': 'var(--aeva-font-size-2xs)',
  '--aeva-badge-padding-md': 'var(--aeva-space-xs) var(--aeva-space-smd)',
  '--aeva-badge-font-size-md': 'var(--aeva-font-size-sm)',
  '--aeva-badge-padding-lg': 'var(--aeva-space-smd) var(--aeva-space-sm)',
  '--aeva-badge-font-size-lg': 'var(--aeva-font-size-sm)',
  '--aeva-badge-delete-size': '16px',
  '--aeva-badge-delete-hover-bg': 'rgba(255, 255, 255, 0.1)',

  // Modal
  '--aeva-modal-bg': 'rgba(31, 41, 55, 0.8)',
  '--aeva-modal-backdrop-bg': 'rgba(0, 0, 0, 0.6)',
  '--aeva-modal-border-color': 'rgba(255, 255, 255, 0.1)',
  '--aeva-modal-border-width': 'var(--aeva-border-thin)',
  '--aeva-modal-shadow-color': 'var(--aeva-shadow-md)',
  '--aeva-modal-blur': 'var(--aeva-blur-lg)',
  '--aeva-modal-padding': 'var(--aeva-space-lg)',
  '--aeva-modal-max-width': '600px',
  '--aeva-modal-border-radius': 'var(--aeva-border-radius-md)',
  '--aeva-modal-shimmer-gradient':
    'linear-gradient(90deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.3) 50%, rgba(255, 255, 255, 0.1) 100%)',

  // Progress
  '--aeva-progress-color': 'var(--aeva-color-blue-500)',
  '--aeva-progress-bg': 'var(--aeva-color-gray-700)',
  '--aeva-progress-thickness': '0.5rem',
  '--aeva-progress-border-radius': '999px',
  '--aeva-progress-label-color': 'var(--aeva-color-gray-100)',
  '--aeva-progress-size-sm': '5rem',
  '--aeva-progress-size-md': '7.5rem',
  '--aeva-progress-size-lg': '10rem',
  '--aeva-progress-animation-duration': '1.5s',
  '--aeva-progress-label-font-size': '0.875rem',

  // Radio
  '--aeva-radio-unchecked-stroke': 'var(--aeva-color-gray-600)',
  '--aeva-radio-unchecked-bg': 'transparent',
  '--aeva-radio-checked-stroke': 'var(--aeva-color-indigo-400)',
  '--aeva-radio-checked-bg': 'var(--aeva-color-indigo-400)',
  '--aeva-radio-checkmark-color': 'var(--aeva-color-white)',
  '--aeva-radio-size': '20px',
  '--aeva-radio-transition': 'var(--aeva-transition-normal)',
  '--aeva-radio-disabled-opacity': '0.5',

  // Checkbox
  '--aeva-checkbox-unchecked-stroke': 'var(--aeva-color-gray-600)',
  '--aeva-checkbox-unchecked-bg': 'transparent',
  '--aeva-checkbox-checked-stroke': 'var(--aeva-color-indigo-400)',
  '--aeva-checkbox-checked-bg': 'var(--aeva-color-indigo-400)',
  '--aeva-checkbox-checkmark-color': 'var(--aeva-color-white)',
  '--aeva-checkbox-size': '20px',
  '--aeva-checkbox-border-radius': '6px',
  '--aeva-checkbox-transition': 'var(--aeva-transition-normal)',
  '--aeva-checkbox-disabled-opacity': '0.5',

  // Rating
  '--aeva-rating-color': '#fbbf24',
  '--aeva-rating-empty-color': 'var(--aeva-color-gray-700)',
  '--aeva-rating-hover-color': '#f59e0b',
  '--aeva-rating-label-color': 'var(--aeva-color-gray-400)',
  '--aeva-rating-size-sm': '16px',
  '--aeva-rating-size-md': '24px',
  '--aeva-rating-size-lg': '32px',

  // Tooltip
  '--aeva-tooltip-bg': 'rgba(0, 0, 0, 0.95)',
  '--aeva-tooltip-color': '#ffffff',
  '--aeva-tooltip-blur': 'var(--aeva-blur-md)',
  '--aeva-tooltip-border-radius': 'var(--aeva-border-radius-md)',
  '--aeva-tooltip-padding': '0.5rem 0.75rem',
  '--aeva-tooltip-font-size': 'var(--aeva-font-size-2xs)',
  '--aeva-tooltip-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.4)',

  // Icon
  '--aeva-icon-bg': 'var(--aeva-color-gray-700)',
  '--aeva-icon-color': 'var(--aeva-color-indigo-400)',
  '--aeva-icon-border-color': 'var(--aeva-color-white)',
  '--aeva-icon-border-width': '2px',
  '--aeva-icon-size-sm': '2.5rem',
  '--aeva-icon-size-md': '3.5rem',
  '--aeva-icon-size-lg': '4.5rem',

  // List Item
  '--aeva-list-item-padding': 'var(--aeva-space-smd) var(--aeva-space-sm)',
  '--aeva-list-item-gap': 'var(--aeva-space-sm)',
  '--aeva-list-item-bg': 'transparent',
  '--aeva-list-item-color': '#f9fafb',
  '--aeva-list-item-hover-bg': 'rgba(255, 255, 255, 0.08)',
  '--aeva-list-item-active-bg': 'rgba(102, 126, 234, 0.15)',
  '--aeva-list-item-active-color': 'var(--aeva-color-indigo-400)',
  '--aeva-list-item-border-radius': '0',
  '--aeva-list-item-transition': 'background-color var(--aeva-transition-normal)',

  // Page
  '--aeva-page-background': '#1a1a1a',
  '--aeva-page-animation-duration': '350ms',
  '--aeva-page-backdrop-bg': 'rgba(0, 0, 0, 0.7)',
  '--aeva-page-z-index': '2000',

  // Popup Menu
  '--aeva-popup-bg': 'rgba(31, 41, 55, 0.8)',
  '--aeva-popup-border-radius': 'var(--aeva-border-radius-md)',
  '--aeva-popup-min-width': '200px',
  '--aeva-popup-max-width': '600px',
  '--aeva-popup-blur': 'var(--aeva-blur-md)',
  '--aeva-popup-border-color': 'rgba(255, 255, 255, 0.1)',
  '--aeva-popup-border-width': 'var(--aeva-border-thin)',
  '--aeva-popup-shadow-color': 'rgba(0, 0, 0, 0.4)',

  // Ripple
  '--aeva-ripple-color': 'currentColor',
  '--aeva-ripple-duration': '600ms',
  '--aeva-ripple-opacity': '0.2',

  // Text
  '--aeva-text-font-family': 'inherit',
  '--aeva-text-max-width': 'none',
  '--aeva-text-display-font-family': 'inherit',
  '--aeva-text-display-weight': '800',
  '--aeva-text-display-line-height': '1.1',
  '--aeva-text-letter-spacing-display': '-0.02em',
  '--aeva-text-heading-font-family': 'inherit',
  '--aeva-text-heading-weight': '700',
  '--aeva-text-heading-line-height': '1.2',
  '--aeva-text-letter-spacing-heading': '-0.01em',
  '--aeva-text-body-font-family': 'inherit',
  '--aeva-text-body-weight': '400',
  '--aeva-text-body-line-height': '1.6',
  '--aeva-text-letter-spacing-body': 'normal',
  '--aeva-text-label-font-family': 'inherit',
  '--aeva-text-label-weight': '500',
  '--aeva-text-label-line-height': '1.4',
  '--aeva-text-letter-spacing-label': '0.01em',
  '--aeva-text-size-xs': 'var(--aeva-font-size-2xs)',
  '--aeva-text-size-sm': 'var(--aeva-font-size-xs)',
  '--aeva-text-size-md': 'var(--aeva-font-size-sm)',
  '--aeva-text-size-lg': 'var(--aeva-font-size-md)',
  '--aeva-text-size-xl': 'var(--aeva-font-size-lg)',
  '--aeva-text-size-2xl': 'var(--aeva-font-size-xl)',
  '--aeva-text-size-3xl': 'var(--aeva-font-size-2xl)',
  '--aeva-text-muted-color': 'var(--aeva-color-gray-400)',
  '--aeva-text-inverse-color': 'var(--aeva-color-gray-900)',
  '--aeva-text-error-color': 'var(--aeva-color-red-400)',
  '--aeva-text-link-color': 'var(--aeva-color-indigo-400)',
  '--aeva-text-link-hover-color': 'var(--aeva-color-indigo-300)',
  '--aeva-text-code-bg': 'rgba(255, 255, 255, 0.1)',

  // Code
  '--aeva-code-bg': '#0d0f12',
  '--aeva-code-header-bg': '#1f2937',
  '--aeva-code-footer-bg': '#0d0f12',
  '--aeva-code-text-color': '#e5e7eb',
  '--aeva-code-title-color': 'rgba(255, 255, 255, 0.3)',
  '--aeva-code-dot-red': '#ff5f56',
  '--aeva-code-dot-yellow': '#ffbd2e',
  '--aeva-code-dot-green': '#27c93f',
  '--aeva-code-copy-btn-bg': 'rgba(255, 255, 255, 0.05)',
  '--aeva-code-copy-btn-color': 'rgba(255, 255, 255, 0.5)',
  '--aeva-code-copy-btn-border': 'rgba(255, 255, 255, 0.1)',
  '--aeva-code-copy-btn-hover-bg': 'rgba(255, 255, 255, 0.1)',
  '--aeva-code-copy-btn-hover-color': 'var(--aeva-color-white)',
  '--aeva-code-copy-btn-hover-border': 'rgba(255, 255, 255, 0.2)',
  '--aeva-code-copy-btn-active-bg': 'rgba(39, 201, 63, 0.15)',
  '--aeva-code-copy-btn-active-color': '#27c93f',
  '--aeva-code-copy-btn-active-border': 'rgba(39, 201, 63, 0.2)',
  '--aeva-code-border-radius': 'var(--aeva-border-radius-md)',

  // Action Bar
  '--aeva-action-bar-bg': 'transparent',
  '--aeva-action-bar-padding': 'var(--aeva-space-sm)',
  '--aeva-action-bar-gap': 'var(--aeva-space-xs)',
  '--aeva-action-bar-border-top': 'none',
  '--aeva-action-bar-border-bottom': 'none',
  '--aeva-action-bar-backdrop-filter': 'none',
  '--aeva-action-bar-drop-shadow': 'none',
  '--aeva-action-bar-sticky-bg': 'rgba(31, 41, 55, 0.95)',
  '--aeva-action-bar-sticky-blur': 'var(--aeva-blur-md)',
  '--aeva-action-bar-glassmorphism-border':
    'var(--aeva-border-thin) solid rgba(255, 255, 255, 0.1)',
  '--aeva-action-bar-glassmorphism-shadow': '0 -2px 8px rgba(0, 0, 0, 0.3)',

  // Carousel
  '--aeva-carousel-height': '25rem',
  '--aeva-carousel-nav-bg': 'rgba(0, 0, 0, 0.6)',
  '--aeva-carousel-nav-color': 'white',
  '--aeva-carousel-nav-hover-bg': 'rgba(0, 0, 0, 0.8)',
  '--aeva-carousel-indicator-color': 'rgba(255, 255, 255, 0.3)',
  '--aeva-carousel-indicator-active-color': 'white',
  '--aeva-carousel-indicator-hover-bg': 'rgba(255, 255, 255, 0.9)',
  '--aeva-carousel-transition-duration': '300ms',

  // List
  '--aeva-list-padding': '0',
  '--aeva-list-gap': '0',
  '--aeva-input-border-radius': 'var(--aeva-border-radius-md)',
  '--aeva-list-border-radius': '23px',

  // Tab
  '--aeva-tab-bg': 'rgba(255, 255, 255, 0.05)',
  '--aeva-tab-active-bg': 'rgba(255, 255, 255, 0.1)',
  '--aeva-tab-padding': 'var(--aeva-space-xxs)',
  '--aeva-tab-gap': 'var(--aeva-space-xxs)',
  '--aeva-tab-border-radius': 'var(--aeva-border-radius-full)',
  '--aeva-tab-transition-duration': 'var(--aeva-duration-normal)',
  '--aeva-tab-transition-timing': 'ease-in-out',

  // Tab Item
  '--aeva-tab-item-font-family': 'inherit',
  '--aeva-tab-item-font-size': 'var(--aeva-font-size-xs)',
  '--aeva-tab-item-padding': 'var(--aeva-space-xs) var(--aeva-space-md)',
  '--aeva-tab-item-border-radius': 'var(--aeva-border-radius-full)',
  '--aeva-tab-item-transition': 'var(--aeva-transition-normal)',
  '--aeva-tab-item-color-active': 'var(--aeva-color-white)',
  '--aeva-tab-item-color-inactive': 'var(--aeva-color-gray-400)',
  '--aeva-tab-item-color-disabled': 'var(--aeva-color-gray-600)',
  '--aeva-tab-item-cursor': 'pointer',
  '--aeva-tab-item-disabled-opacity': '0.5',
  '--aeva-tab-item-focus-ring': '2px solid rgba(129, 140, 248, 0.4)',

  // Toast
  '--aeva-toast-bg': 'rgba(31, 41, 55, 0.9)',
  '--aeva-toast-text-color': 'var(--aeva-color-gray-50)',
  '--aeva-toast-close-color': 'var(--aeva-color-gray-400)',
  '--aeva-toast-close-hover-color': 'var(--aeva-color-white)',
  '--aeva-toast-border-radius': '12px',
  '--aeva-toast-padding': 'var(--aeva-space-sm) var(--aeva-space-md)',
  '--aeva-toast-min-width': '300px',
  '--aeva-toast-max-width': '500px',
  '--aeva-toast-blur': 'var(--aeva-blur-md)',
  '--aeva-toast-border-color': 'rgba(255, 255, 255, 0.1)',
  '--aeva-toast-border-width': 'var(--aeva-border-thin)',
  '--aeva-toast-shadow-color': 'var(--aeva-shadow-sm)',
  '--aeva-toast-close-hover-bg': 'rgba(255, 255, 255, 0.1)',
  '--aeva-toast-success-bg': 'rgba(6, 78, 59, 0.9)',
  '--aeva-toast-success-border': 'rgba(16, 185, 129, 0.2)',
  '--aeva-toast-success-icon': '#34d399',
  '--aeva-toast-error-bg': 'rgba(127, 29, 29, 0.9)',
  '--aeva-toast-error-border': 'rgba(239, 68, 68, 0.2)',
  '--aeva-toast-error-icon': '#f87171',
  '--aeva-toast-warning-bg': 'rgba(120, 53, 15, 0.9)',
  '--aeva-toast-warning-border': 'rgba(245, 158, 11, 0.2)',
  '--aeva-toast-warning-icon': '#fbbf24',
  '--aeva-toast-info-bg': 'rgba(30, 58, 138, 0.9)',
  '--aeva-toast-info-border': 'rgba(59, 130, 246, 0.2)',
  '--aeva-toast-info-icon': '#60a5fa',

  // Grid & Stack Gaps
  '--aeva-grid-gap-none': '0',
  '--aeva-grid-gap-xs': 'var(--aeva-space-xxs)',
  '--aeva-grid-gap-sm': 'var(--aeva-space-xs)',
  '--aeva-grid-gap-md': 'var(--aeva-space-sm)',
  '--aeva-grid-gap-lg': 'var(--aeva-space-md)',
  '--aeva-grid-gap-xl': 'var(--aeva-space-lg)',
  '--aeva-grid-auto-min-width': '250px',
  '--aeva-grid-auto-max-width': '1fr',

  '--aeva-stack-gap-none': '0',
  '--aeva-stack-gap-xs': 'var(--aeva-space-xxs)',
  '--aeva-stack-gap-sm': 'var(--aeva-space-xs)',
  '--aeva-stack-gap-md': 'var(--aeva-space-sm)',
  '--aeva-stack-gap-lg': 'var(--aeva-space-md)',
  '--aeva-stack-gap-xl': 'var(--aeva-space-lg)',

  // Bento Grid
  '--aeva-bento-grid-gap': 'var(--aeva-space-sm)',
  '--aeva-bento-grid-min-height': '200px',

  // Section
  '--aeva-section-gap': '0',
  '--aeva-section-padding': '0',
  '--aeva-section-header-padding': '0',
  '--aeva-section-body-padding': '0',
  '--aeva-section-footer-padding': '0',

  // Sidebar
  '--aeva-sidebar-bg': 'var(--aeva-color-gray-800)',
  '--aeva-sidebar-width-sm': '12.5rem',
  '--aeva-sidebar-width-md': '17.5rem',
  '--aeva-sidebar-width-lg': '20rem',
  '--aeva-sidebar-icon-width': '4.5rem',
  '--aeva-sidebar-transition': 'var(--aeva-transition-slow)',
  '--aeva-sidebar-z-index': 'var(--aeva-z-sidebar)',
  '--aeva-sidebar-shadow': 'var(--aeva-shadow-md)',
  '--aeva-sidebar-backdrop-bg': 'rgba(0, 0, 0, 0.7)',
  '--aeva-sidebar-border': 'var(--aeva-border-thin) solid rgba(255, 255, 255, 0.1)',
  '--aeva-sidebar-glassmorphism-bg': 'rgba(31, 41, 55, 0.95)',
  '--aeva-sidebar-glassmorphism-border': 'rgba(255, 255, 255, 0.1)',
  '--aeva-sidebar-scrollbar-thumb': 'var(--aeva-color-gray-600)',
  '--aeva-sidebar-scrollbar-thumb-hover': 'var(--aeva-color-gray-500)',

  // Global Scrollbar
  '--aeva-scrollbar-width': '8px',
  '--aeva-scrollbar-thumb': 'var(--aeva-color-gray-600)',
  '--aeva-scrollbar-thumb-hover': 'var(--aeva-color-gray-500)',
  '--aeva-scrollbar-track': 'transparent',

  // Container
  '--aeva-container-max-width-sm': '40rem',
  '--aeva-container-max-width-md': '48rem',
  '--aeva-container-max-width-lg': '64rem',
  '--aeva-container-max-width-xl': '80rem',
  '--aeva-container-max-width-full': '100%',
  '--aeva-container-padding-none': '0',
  '--aeva-container-padding-sm': 'var(--aeva-space-sm)',
  '--aeva-container-padding-md': 'var(--aeva-space-md)',
  '--aeva-container-padding-lg': 'var(--aeva-space-lg)',

  // Grid Item
  '--aeva-grid-item-min-height': 'auto',

  // Masonry
  '--aeva-masonry-gap': '16px',
  '--aeva-masonry-column-count': 'auto',

  // Table (Documentation)
  '--aeva-table-header-border': '2px solid rgba(255, 255, 255, 0.1)',
  '--aeva-table-row-border': '1px solid rgba(255, 255, 255, 0.05)',
  '--aeva-table-header-color': 'var(--aeva-color-white)',
  '--aeva-table-text-color': 'var(--aeva-color-white)',
  '--aeva-table-accent-color': 'var(--aeva-primary-color)',
  '--aeva-table-header-bg': 'rgba(255, 255, 255, 0.05)',
  '--aeva-table-row-bg': 'transparent',

  // Accordion
  '--aeva-accordion-bg': 'transparent',
  '--aeva-accordion-border-radius': 'var(--aeva-border-radius-md)',
  '--aeva-accordion-item-border-color': 'var(--aeva-color-gray-700)',
  '--aeva-accordion-header-padding': 'var(--aeva-space-md)',
  '--aeva-accordion-content-padding': 'var(--aeva-space-md)',
  '--aeva-accordion-header-hover-bg': 'rgba(255, 255, 255, 0.05)',
  '--aeva-accordion-transition': 'var(--aeva-transition-normal)',

  // Pagination
  '--aeva-pagination-gap': 'var(--aeva-space-xs)',
  '--aeva-pagination-btn-size': '40px',
  '--aeva-pagination-btn-bg': 'var(--aeva-color-gray-800)',
  '--aeva-pagination-btn-color': 'var(--aeva-color-gray-300)',
  '--aeva-pagination-btn-hover-bg': 'var(--aeva-color-gray-700)',
  '--aeva-pagination-btn-active-bg': 'var(--aeva-primary-color)',
  '--aeva-pagination-btn-active-color': 'var(--aeva-color-gray-950)',
  '--aeva-pagination-btn-border-radius': '12px',

  // Process
  '--aeva-process-gap': 'var(--aeva-space-md)',
  '--aeva-step-circle-size': '32px',
  '--aeva-step-line-thickness': '2px',
  '--aeva-step-color-pending': 'var(--aeva-color-gray-600)',
  '--aeva-step-color-active': 'var(--aeva-primary-color)',
  '--aeva-step-color-completed': 'var(--aeva-primary-color)',
  '--aeva-step-color-error': 'var(--aeva-color-red-600)',
  '--aeva-step-line-color': 'var(--aeva-color-gray-800)',
  '--aeva-step-circle-bg': 'var(--aeva-color-gray-900)',

  // Slider
  '--aeva-slider-track-height': '6px',
  '--aeva-slider-track-bg': 'var(--aeva-color-gray-700)',
  '--aeva-slider-fill-bg': 'var(--aeva-primary-color)',
  '--aeva-slider-thumb-size': '18px',
  '--aeva-slider-thumb-bg': 'var(--aeva-primary-color)',
  '--aeva-slider-thumb-border': '2px solid var(--aeva-primary-color)',
  '--aeva-slider-thumb-shadow': '0 2px 6px rgba(0, 0, 0, 0.3)',

  // Switch
  '--aeva-switch-width': '44px',
  '--aeva-switch-height': '24px',
  '--aeva-switch-track-bg': 'var(--aeva-color-gray-700)',
  '--aeva-switch-track-checked-bg': 'var(--aeva-primary-color)',
  '--aeva-switch-thumb-bg': 'var(--aeva-color-white)',
  '--aeva-switch-thumb-size': '18px',
  '--aeva-switch-thumb-shadow': '0 2px 4px rgba(0, 0, 0, 0.4)',
  '--aeva-switch-transition': '300ms cubic-bezier(0.4, 0, 0.2, 1)',
  '--aeva-switch-elastic-transition': '400ms cubic-bezier(0.34, 1.56, 0.64, 1)',
};
