import { ThemeVariables } from '../types';

export const lightTheme: ThemeVariables = {
    // Global
    '--aeva-font-family': "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif",
    '--aeva-page-bg': '#ffffff',
    '--aeva-page-gradient': 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
    '--aeva-primary-color': '#667eea',
    '--aeva-primary-hover': '#5568d3',
    '--aeva-secondary-color': '#6c757d',
    '--aeva-text-color': '#1a1a1a',
    '--aeva-text-muted': '#6b7280',
    '--aeva-card-bg': '#ffffff',
    '--aeva-card-border-color': '#e5e7eb',
    '--aeva-card-border-hover-color': '#667eea',
    '--aeva-card-border-radius': '12px',
    '--aeva-card-transition': 'all 0.2s ease',
    '--aeva-card-padding-sm': '1rem',
    '--aeva-card-padding-md': '1.5rem',
    '--aeva-card-padding-lg': '2rem',

    // Button
    '--aeva-button-font-family': "inherit",
    '--aeva-button-border-radius': '50vh',
    '--aeva-button-transition': 'all 0.2s ease-in-out',
    '--aeva-button-gap': '8px',
    '--aeva-button-focus-ring-color': '#667eea',
    '--aeva-button-focus-ring-width': '3px',
    '--aeva-button-focus-ring-offset': '2px',
    '--aeva-button-primary-bg': '#667eea',
    '--aeva-button-primary-color': '#ffffff',
    '--aeva-button-primary-hover-bg': '#5568d3',
    '--aeva-button-primary-active-bg': '#4451b8',
    '--aeva-button-secondary-bg': '#6c757d',
    '--aeva-button-secondary-color': '#ffffff',
    '--aeva-button-secondary-hover-bg': '#5a6268',
    '--aeva-button-secondary-active-bg': '#545b62',
    '--aeva-button-outline-border-color': '#667eea',
    '--aeva-button-outline-color': '#667eea',
    '--aeva-button-outline-hover-bg': 'rgba(102, 126, 234, 0.1)',
    '--aeva-button-outline-active-bg': 'rgba(102, 126, 234, 0.2)',
    '--aeva-button-ghost-color': '#667eea',
    '--aeva-button-ghost-hover-bg': 'rgba(102, 126, 234, 0.1)',
    '--aeva-button-ghost-active-bg': 'rgba(102, 126, 234, 0.2)',
    '--aeva-button-danger-bg': '#dc3545',
    '--aeva-button-danger-color': '#ffffff',
    '--aeva-button-danger-hover-bg': '#c82333',
    '--aeva-button-danger-active-bg': '#bd2130',
    '--aeva-button-disabled-opacity': '0.5',
    '--aeva-button-disabled-cursor': 'not-allowed',
    '--aeva-button-padding-sm': '8px 32px',
    '--aeva-button-font-size-sm': '14px',
    '--aeva-button-padding-md': '12px 48px',
    '--aeva-button-font-size-md': '16px',
    '--aeva-button-padding-lg': '16px 64px',
    '--aeva-button-font-size-lg': '18px',
    '--aeva-button-icon-padding-sm': '10px',
    '--aeva-button-icon-width-sm': '44px',
    '--aeva-button-icon-padding-md': '12px',
    '--aeva-button-icon-width-md': '44px',
    '--aeva-button-icon-padding-lg': '14px',
    '--aeva-button-icon-width-lg': '48px',

    // Input
    '--aeva-input-font-family': "inherit",
    '--aeva-input-border-radius': '8px',
    '--aeva-input-transition': 'all 0.2s ease-in-out',
    '--aeva-input-bg': '#ffffff',
    '--aeva-input-border-color': '#d1d5db',
    '--aeva-input-text-color': '#1a1a1a',
    '--aeva-input-placeholder-color': '#9ca3af',
    '--aeva-input-error-border-color': '#dc2626',
    '--aeva-input-focus-border-color': '#667eea',
    '--aeva-input-focus-ring-color': 'rgba(102, 126, 234, 0.3)',
    '--aeva-input-focus-ring-width': '3px',
    '--aeva-input-focus-ring-offset': '0px',
    '--aeva-input-hover-border-color': '#9ca3af',
    '--aeva-input-disabled-bg': '#f3f4f6',
    '--aeva-input-disabled-border-color': '#e5e7eb',
    '--aeva-input-disabled-text-color': '#9ca3af',
    '--aeva-input-disabled-opacity': '0.6',
    '--aeva-input-flat-bg': 'transparent',
    '--aeva-input-flat-hover-bg': 'rgba(0, 0, 0, 0.05)',
    '--aeva-input-flat-focus-bg': 'rgba(0, 0, 0, 0.08)',
    '--aeva-input-padding-sm': '8px 12px',
    '--aeva-input-font-size-sm': '14px',
    '--aeva-input-height-sm': '36px',
    '--aeva-input-padding-md': '12px 16px',
    '--aeva-input-font-size-md': '16px',
    '--aeva-input-height-md': '44px',
    '--aeva-input-padding-lg': '16px 20px',
    '--aeva-input-font-size-lg': '18px',
    '--aeva-input-height-lg': '52px',
    '--aeva-input-multiline-min-height': '100px',

    // Badge
    '--aeva-badge-font-family': "inherit",
    '--aeva-badge-border-radius': '16px',
    '--aeva-badge-transition': 'all 0.2s ease-in-out',
    '--aeva-badge-gap': '6px',
    '--aeva-badge-primary-bg': '#e8eaf6',
    '--aeva-badge-primary-color': '#3f51b5',
    '--aeva-badge-primary-border': '#c5cae9',
    '--aeva-badge-secondary-bg': '#f5f5f5',
    '--aeva-badge-secondary-color': '#616161',
    '--aeva-badge-secondary-border': '#e0e0e0',
    '--aeva-badge-success-bg': '#e8f5e9',
    '--aeva-badge-success-color': '#2e7d32',
    '--aeva-badge-success-border': '#c8e6c9',
    '--aeva-badge-warning-bg': '#fff3e0',
    '--aeva-badge-warning-color': '#e65100',
    '--aeva-badge-warning-border': '#ffe0b2',
    '--aeva-badge-danger-bg': '#ffebee',
    '--aeva-badge-danger-color': '#c62828',
    '--aeva-badge-danger-border': '#ffcdd2',
    '--aeva-badge-info-bg': '#e3f2fd',
    '--aeva-badge-info-color': '#1565c0',
    '--aeva-badge-info-border': '#bbdefb',
    '--aeva-badge-padding-sm': '4px 10px',
    '--aeva-badge-font-size-sm': '12px',
    '--aeva-badge-padding-md': '6px 12px',
    '--aeva-badge-font-size-md': '14px',
    '--aeva-badge-padding-lg': '8px 16px',
    '--aeva-badge-font-size-lg': '16px',
    '--aeva-badge-delete-size': '16px',
    '--aeva-badge-delete-hover-bg': 'rgba(0, 0, 0, 0.1)',

    // Modal
    '--aeva-modal-bg': 'rgba(255, 255, 255, 0.8)',
    '--aeva-modal-backdrop-bg': 'rgba(0, 0, 0, 0.4)',
    '--aeva-modal-border-color': 'rgba(255, 255, 255, 0.5)',
    '--aeva-modal-shadow-color': 'rgba(0, 0, 0, 0.1)',
    '--aeva-modal-blur': '20px',
    '--aeva-modal-padding': '2rem',
    '--aeva-modal-max-width': '600px',
    '--aeva-modal-border-radius': '24px',
    '--aeva-modal-shimmer-gradient': 'linear-gradient(90deg, rgba(255, 255, 255, 0.6) 0%, rgba(255, 255, 255, 0.1) 50%, rgba(255, 255, 255, 0.6) 100%)',

    // Progress
    '--aeva-progress-color': '#667eea',
    '--aeva-progress-bg': '#e5e7eb',
    '--aeva-progress-thickness': '8px',
    '--aeva-progress-border-radius': '999px',
    '--aeva-progress-label-color': '#1f2937',
    '--aeva-progress-size-sm': '80px',
    '--aeva-progress-size-md': '120px',
    '--aeva-progress-size-lg': '160px',
    '--aeva-progress-animation-duration': '1.5s',
    '--aeva-progress-label-font-size': '14px',

    // Radio
    '--aeva-radio-unchecked-stroke': '#9ca3af',
    '--aeva-radio-checked-stroke': '#667eea',
    '--aeva-radio-checked-bg': '#667eea',
    '--aeva-radio-checkmark-color': '#ffffff',
    '--aeva-radio-size': '20px',
    '--aeva-radio-transition': 'all 0.2s ease-in-out',
    '--aeva-radio-disabled-opacity': '0.5',

    // Checkbox
    '--aeva-checkbox-unchecked-stroke': '#9ca3af',
    '--aeva-checkbox-checked-stroke': '#667eea',
    '--aeva-checkbox-checked-bg': '#667eea',
    '--aeva-checkbox-checkmark-color': '#ffffff',
    '--aeva-checkbox-size': '20px',
    '--aeva-checkbox-border-radius': '6px',
    '--aeva-checkbox-transition': 'all 0.2s ease-in-out',
    '--aeva-checkbox-disabled-opacity': '0.5',

    // Rating
    '--aeva-rating-color': '#fbbf24',
    '--aeva-rating-empty-color': '#e5e7eb',
    '--aeva-rating-hover-color': '#f59e0b',
    '--aeva-rating-label-color': '#6b7280',
    '--aeva-rating-size-sm': '16px',
    '--aeva-rating-size-md': '24px',
    '--aeva-rating-size-lg': '32px',

    // Tooltip
    '--aeva-tooltip-bg': 'rgba(0, 0, 0, 0.9)',
    '--aeva-tooltip-color': '#ffffff',
    '--aeva-tooltip-blur': '10px',
    '--aeva-tooltip-border-radius': '8px',
    '--aeva-tooltip-padding': '0.5rem 0.75rem',
    '--aeva-tooltip-font-size': '0.875rem',
    '--aeva-tooltip-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.2)',

    // Icon
    '--aeva-icon-bg': '#f5f5f5',
    '--aeva-icon-color': '#667eea',
    '--aeva-icon-border-color': '#000000',
    '--aeva-icon-border-width': '2px',
    '--aeva-icon-size-sm': '40px',
    '--aeva-icon-size-md': '56px',
    '--aeva-icon-size-lg': '72px',

    // List Item
    '--aeva-list-item-padding': '12px 16px',
    '--aeva-list-item-gap': '16px',
    '--aeva-list-item-bg': 'transparent',
    '--aeva-list-item-color': '#1a1a1a',
    '--aeva-list-item-hover-bg': 'rgba(0, 0, 0, 0.04)',
    '--aeva-list-item-active-bg': 'rgba(102, 126, 234, 0.08)',
    '--aeva-list-item-border-radius': '0',
    '--aeva-list-item-transition': 'background-color 0.2s ease',

    // Page
    '--aeva-page-background': 'white',
    '--aeva-page-animation-duration': '350ms',
    '--aeva-page-backdrop-bg': 'rgba(0, 0, 0, 0.5)',
    '--aeva-page-z-index': '2000',

    // Popup Menu
    '--aeva-popup-bg': 'rgba(255, 255, 255, 0.7)',
    '--aeva-popup-border-radius': '23px',
    '--aeva-popup-min-width': '200px',
    '--aeva-popup-max-width': '600px',
    '--aeva-popup-blur': '10px',
    '--aeva-popup-border-color': 'rgba(255, 255, 255, 0.5)',
    '--aeva-popup-shadow-color': 'rgba(0, 0, 0, 0.1)',

    // Ripple
    '--aeva-ripple-color': 'currentColor',
    '--aeva-ripple-duration': '600ms',
    '--aeva-ripple-opacity': '0.15',

    // Tab Item
    '--aeva-tab-item-font-family': "inherit",
    '--aeva-tab-item-font-size': '14px',
    '--aeva-tab-item-padding': '8px 16px',
    '--aeva-tab-item-border-radius': '8px',
    '--aeva-tab-item-transition': 'color 0.2s ease-in-out',
    '--aeva-tab-item-color-active': '#ffffff',
    '--aeva-tab-item-color-inactive': 'rgba(255, 255, 255, 0.6)',
    '--aeva-tab-item-color-disabled': 'rgba(255, 255, 255, 0.3)',
    '--aeva-tab-item-cursor': 'pointer',
    '--aeva-tab-item-disabled-opacity': '0.5',

    // Text
    '--aeva-text-font-family': "inherit",
    '--aeva-text-max-width': 'none',
    '--aeva-text-display-font-family': "inherit",
    '--aeva-text-display-weight': '800',
    '--aeva-text-display-line-height': '1.1',
    '--aeva-text-letter-spacing-display': '-0.02em',
    '--aeva-text-heading-font-family': "inherit",
    '--aeva-text-heading-weight': '700',
    '--aeva-text-heading-line-height': '1.2',
    '--aeva-text-letter-spacing-heading': '-0.01em',
    '--aeva-text-body-font-family': "inherit",
    '--aeva-text-body-weight': '400',
    '--aeva-text-body-line-height': '1.6',
    '--aeva-text-letter-spacing-body': 'normal',
    '--aeva-text-label-font-family': "inherit",
    '--aeva-text-label-weight': '500',
    '--aeva-text-label-line-height': '1.4',
    '--aeva-text-letter-spacing-label': '0.01em',
    '--aeva-text-size-xs': '0.75rem',
    '--aeva-text-size-sm': '0.875rem',
    '--aeva-text-size-md': '1rem',
    '--aeva-text-size-lg': '1.125rem',
    '--aeva-text-size-xl': '1.25rem',
    '--aeva-text-size-2xl': '1.5rem',
    '--aeva-text-size-3xl': '1.875rem',
    '--aeva-text-muted-color': '#6b7280',
    '--aeva-text-inverse-color': '#ffffff',
    '--aeva-text-error-color': '#dc2626',
    '--aeva-text-link-color': '#667eea',
    '--aeva-text-link-hover-color': '#5568d3',
    '--aeva-text-code-bg': 'rgba(0, 0, 0, 0.05)',

    // Action Bar
    '--aeva-action-bar-bg': 'transparent',
    '--aeva-action-bar-padding': '1rem',
    '--aeva-action-bar-gap': '0.75rem',
    '--aeva-action-bar-border-top': 'none',
    '--aeva-action-bar-border-bottom': 'none',
    '--aeva-action-bar-backdrop-filter': 'none',
    '--aeva-action-bar-drop-shadow': 'none',
    '--aeva-action-bar-sticky-bg': 'rgba(255, 255, 255, 0.95)',
    '--aeva-action-bar-sticky-blur': '10px',
    '--aeva-action-bar-glassmorphism-border': '1px solid rgba(0, 0, 0, 0.1)',
    '--aeva-action-bar-glassmorphism-shadow': '0 -2px 8px rgba(0, 0, 0, 0.05)',

    // Carousel
    '--aeva-carousel-height': '400px',
    '--aeva-carousel-nav-bg': 'rgba(0, 0, 0, 0.5)',
    '--aeva-carousel-nav-color': 'white',
    '--aeva-carousel-nav-hover-bg': 'rgba(0, 0, 0, 0.7)',
    '--aeva-carousel-indicator-color': 'rgba(255, 255, 255, 0.5)',
    '--aeva-carousel-indicator-active-color': 'white',
    '--aeva-carousel-indicator-hover-bg': 'rgba(255, 255, 255, 0.7)',
    '--aeva-carousel-transition-duration': '300ms',

    // List
    '--aeva-list-padding': '0',
    '--aeva-list-gap': '0',
    '--aeva-list-border-radius': '23px',

    // Tab
    '--aeva-tab-bg': 'rgba(0, 0, 0, 0.05)',
    '--aeva-tab-active-bg': '#ffffff',
    '--aeva-tab-padding': '12px',
    '--aeva-tab-gap': '12px',
    '--aeva-tab-border-radius': '50vh',
    '--aeva-tab-transition-duration': '300ms',
    '--aeva-tab-transition-timing': 'cubic-bezier(0.4, 0, 0.2, 1)',

    // Toast
    '--aeva-toast-bg': 'rgba(255, 255, 255, 0.9)',
    '--aeva-toast-border-radius': '12px',
    '--aeva-toast-padding': '1rem 1.25rem',
    '--aeva-toast-min-width': '300px',
    '--aeva-toast-max-width': '500px',
    '--aeva-toast-blur': '10px',
    '--aeva-toast-border-color': 'rgba(255, 255, 255, 0.5)',
    '--aeva-toast-shadow-color': 'rgba(0, 0, 0, 0.1)',
    '--aeva-toast-close-hover-bg': 'rgba(0, 0, 0, 0.1)',

    // Grid & Stack Gaps
    '--aeva-grid-gap-none': '0',
    '--aeva-grid-gap-xs': '0.25rem',
    '--aeva-grid-gap-sm': '0.5rem',
    '--aeva-grid-gap-md': '1rem',
    '--aeva-grid-gap-lg': '1.5rem',
    '--aeva-grid-gap-xl': '2rem',
    '--aeva-grid-auto-min-width': '250px',
    '--aeva-grid-auto-max-width': '1fr',

    '--aeva-stack-gap-none': '0',
    '--aeva-stack-gap-xs': '0.25rem',
    '--aeva-stack-gap-sm': '0.5rem',
    '--aeva-stack-gap-md': '1rem',
    '--aeva-stack-gap-lg': '1.5rem',
    '--aeva-stack-gap-xl': '2rem',

    // Bento Grid
    '--aeva-bento-grid-gap': '1rem',
    '--aeva-bento-grid-min-height': '200px',

    // Section
    '--aeva-section-gap': '0',
    '--aeva-section-padding': '0',
    '--aeva-section-header-padding': '0',
    '--aeva-section-body-padding': '0',
    '--aeva-section-footer-padding': '0',

    // Sidebar
    '--aeva-sidebar-bg': '#ffffff',
    '--aeva-sidebar-width-sm': '200px',
    '--aeva-sidebar-width-md': '280px',
    '--aeva-sidebar-width-lg': '320px',
    '--aeva-sidebar-icon-width': '72px',
    '--aeva-sidebar-transition': '0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    '--aeva-sidebar-z-index': '1000',
    '--aeva-sidebar-shadow': '2px 0 8px rgba(0, 0, 0, 0.15)',
    '--aeva-sidebar-backdrop-bg': 'rgba(0, 0, 0, 0.5)',
    '--aeva-sidebar-border': '1px solid #e5e7eb',
    '--aeva-sidebar-glassmorphism-bg': 'rgba(255, 255, 255, 0.95)',
    '--aeva-sidebar-glassmorphism-border': 'rgba(0, 0, 0, 0.1)',
    '--aeva-sidebar-scrollbar-thumb': '#d1d5db',
    '--aeva-sidebar-scrollbar-thumb-hover': '#9ca3af',

    // Container
    '--aeva-container-max-width-sm': '640px',
    '--aeva-container-max-width-md': '768px',
    '--aeva-container-max-width-lg': '1024px',
    '--aeva-container-max-width-xl': '1280px',
    '--aeva-container-max-width-full': '100%',
    '--aeva-container-padding-none': '0',
    '--aeva-container-padding-sm': '1rem',
    '--aeva-container-padding-md': '1.5rem',
    '--aeva-container-padding-lg': '2rem',

    // Grid Item
    '--aeva-grid-item-min-height': 'auto',

    // Masonry
    '--aeva-masonry-gap': '16px',
    '--aeva-masonry-column-count': 'auto'
};
